apiVersion: openchoreo.dev/v1alpha1
kind: ClusterResourceTemplate
metadata:
  name: secret-file-external
spec:
  id: secret-file-external
  forEach: ${configurations.toSecretFileList()}
  var: file
  template:
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: ${file.resourceName}
      namespace: ${metadata.namespace}
    spec:
      refreshInterval: 15s
      secretStoreRef:
        name: ${dataplane.secretStore}
        kind: ClusterSecretStore
      target:
        name: ${file.resourceName}
        creationPolicy: Owner
      data:
        - secretKey: ${file.name}
          remoteRef:
            key: ${file.remoteRef.key}
            property: |
              ${has(file.remoteRef.property) ? file.remoteRef.property : oc_omit()}
